### PR TITLE
JBPM-4664:advanced and baisc mode for process instance include: new d…

### PR DESCRIPTION
**Pull request by bxf12315**
…etails tab page and create module jbpm-console-ng-generic-preferences

### CODE REVIEW

**Comment by bxf12315** [comment]
@Salaboy hi i updated this PR, as we discuss content.(include: refacing Dataset Process instance list)
Update to bootstrap3.
The PR dependency on PR droolsjbpm/droolsjbpm-build-bootstrap#64 
Please review it.

**Comment by bxf12315** [comment]
@porcelli @Salaboy @cristianonicolai @nmirasch 
I think the PR to large, So separate it to two PR.
1 https://github.com/droolsjbpm/jbpm-console-ng/pull/210
add jbpm-console-ng-generic-preferences for multiple view mode and enable multiple view mode for process definition
2 I will raise it.
advanced and basic mode for process instance

**Comment by manstis** [comment]
@bxf12315 Is this PR to be closed, replaced by #210 and another (to follow)?

**Comment by bxf12315** [comment]
@manstis yes, this PR will be closed.

**Pull request closed without merging**
