### PR TITLE
Remove jbpm-console-ng-ht-showcase

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by csadilek** [comment]
Deleting unneeded code will always get a +1 from me :). Any objections?

**Comment by porcelli** [comment]
@Salaboy you did this, any objections to remove?

**Comment by Salaboy** [comment]
+1 , my only objection is that this module was created to test the modularity of the modules inside the jbpm console ng, but we will need to work on that later on anyway.. and probably using a different approach. So I'm ok with removing this now

**Comment by porcelli** [comment]
https://github.com/droolsjbpm/jbpm-console-ng/commit/83ce60d38f18bcf02c8a7c9f8607f1b063bc90f6

**Pull request closed without merging**
