### PR TITLE
changes in license header

### PR DESCRIPTION
**Pull request by mbiarnes**
tested locally after the changes with mvn clean install -Dfull -TC1 -- build was successful

### CODE REVIEW

**Comment by csadilek** [comment]
@mbiarnes there's something wrong with this one as it adds files i.e. ProcessDashboardViewImpl.java

**Comment by csadilek** [comment]
@mbiarnes also DataSetHandler and DataSetHandlerImpl see https://github.com/droolsjbpm/jbpm-console-ng/pull/244/files

**Comment by mbiarnes** [comment]
@csadilek 2nd try - this time without files that shouldn't be there. Thank you for reviewing so attentively the PRs.

**Comment by csadilek** [comment]
master: 53f5fb51a2fdd31503893cd1a46a6e2b740c921d

**Pull request closed without merging**
