### PR TITLE
BZ1320357 - [GSS] (6.2.z) Default Tasks List filters doesn't keep up …

### PR DESCRIPTION
**Pull request by nmirasch**
…with user's roles changes

### CODE REVIEW

**Comment by cristianonicolai** [comment]
+1 thanks @nmirasch

**Comment by cristianonicolai** [comment]
@nmirasch this PR now has conflicts, please verify.

**Comment by nmirasch** [comment]
@cristianonicolai  done. Thanks!

**Comment by cristianonicolai** [comment]
Thanks @nmirasch 

e9928f386e3a6266f38918e57a5f08d86c7a0c0b

**Pull request closed without merging**
