### PR TITLE
JBPM-4958 and BZ-1160144 Update process instances and tasks search

### PR DESCRIPTION
**Pull request by cristianonicolai**
Allow searching by task id and process instance id if search criteria is only numbers
Search for process definition id using exact match

### CODE REVIEW

**Comment by psiroky** [comment]
Is this one ready to go as well, since the master one https://github.com/droolsjbpm/jbpm-console-ng/pull/337 was +1ed?

**Comment by cristianonicolai** [comment]
@psiroky I would say so.

**Comment by csadilek** [comment]
Catching up on PRs. Unfortunately, this one is in conflict now. Can you please resolve. Thanks.

**Comment by cristianonicolai** [comment]
@csadilek done ;)

**Comment by csadilek** [comment]
master: 8a41da5fa1e68dcf4fda6aca3510ba33f288933a

**Pull request closed without merging**
