### PR TITLE
BZ-1248020 - JobExecutor: Job Service Settings dialog active despite …

### PR DESCRIPTION
**Pull request by mswiderski**
…disabled job executor

### CODE REVIEW

**Comment by cristianonicolai** [comment]
+1

**Comment by csadilek** [comment]
Is this confirmed for 6.3.x?

**Comment by mswiderski** [comment]
yes, it is confirmed for 6.3.x, though feel free to wait for @etirelli or @krisv to drop a note too

**Comment by etirelli** [comment]
+1 to merge, it was approved for inclusion in 6.3.x.

**Comment by csadilek** [comment]
Thanks.

6.3.x: f704c26c72a9a134b7310a7b157bdc87bfc36ff1

**Pull request closed without merging**
