### PR TITLE
JBPM-5349: Drilldown in Process and task dashboard broken

### PR DESCRIPTION
**Pull request by dgutierr**
Verified on a SDM + wf10/kie-server setup.

Tests have been also adapted to the new metric component.

@cristianonicolai Can you verify please?

### CODE REVIEW

**Comment by dgutierr** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
@dgutierr when I select something on either _Processes By Type_ or _Tasks By Process_ all displayers get updated but the one I selected, is that expected behavior?

**Comment by jhrcek** [comment]
@dgutierr I reported this behavior described by @cristianonicolai  as a regression in JBPM-5349, because in previous versions ALL the charts were updated including the one you click for filtering.

**Comment by dgutierr** [comment]
@jhrcek @cristianonicolai  I will check that, fix it and add the corresponding test case as well to avoid regressions. Thanks mates!

**Comment by dgutierr** [comment]
@cristianonicolai I fixed the issue and now everything works as expected.  Can you verify it again please?

**Comment by cristianonicolai** [comment]
Thanks @dgutierr. Unfortunately, looks like the problem still there. Also the aggregate card colors seems to have blue background instead of white.
Here is what I get when selecting a specific process type:
selection_094

**Comment by dgutierr** [comment]
@cristianonicolai weird. it looks like you were not running the latest changes I pushed.  @nmirasch Can you take a look and check if the dashboard looks fine in your env? Thanks!

**Comment by nmirasch** [comment]
@cristianonicolai, @dgutierr this is how I see the screen in my environment (chrome and firefox), I think the colour of the boxes is right  
jira_5349

**Comment by dgutierr** [comment]
Thanks a lot @nmirasch . That's exact the expected behaviour. @cristianonicolai Can you please double check your setup?

**Comment by cristianonicolai** [comment]
thanks @nmirasch.
@dgutierr sorry, I can confirm that I'm getting the same as @nmirasch.
As you can see in the last image, _Processes By Type_, still not filtered when Evaluation process is selected. All other widgets are filtered but this one, same goes for _Tasks By Process_.

**Comment by dgutierr** [comment]
@cristianonicolai  The  "Processes By Type" chart is acting as a selector. It should not be updated since it reflects the selection made by the user. This is the expected behaviour :-)

**Comment by cristianonicolai** [comment]
@dgutierr @jhrcek, ok so I guess there is some misunderstanding here. I checked a previous version and the current behavior seems fine, whatever graph is used to drill down the information remains unchanged. @jhrcek, regarding JBPM-5349, this fixes part 1, but part 2 is just the expected behavior. WDYT?

**Comment by jhrcek** [comment]
@cristianonicolai I verified the previous behavior with 6.4 product and it turns out I made a mistake: the problem described in 2 in the jira is actually expected behavior - only the first problem needed to be fixed. If that's the case this PR can be merge. Sorry for confusion.

**Comment by cristianonicolai** [comment]
@jhrcek no worries, thanks for clarifying that.

**Pull request merged**
