### PR TITLE
JBPM-4900 - Enhance TaskList Search capability

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/droolsjbpm/droolsjbpm-integration/pull/280

### CODE REVIEW

**Comment by cristianonicolai** [comment]
+1

**Comment by csadilek** [comment]
master: 957b26d9a3c520f1232fbc55a178f22d91b34d77

**Comment by psiroky** [comment]
It seems that merging this without the peer RPs for jbpm and droolsjbpm-integration causes the workbench to fail during deployment with `java.lang.ClassNotFoundException: org.jbpm.kie.services.impl.query.persistence.QueryDefinitionEntity`. It seems those other PRs will take some time to review (they are big), so I would propose to revert this change (+ the one in kie-wb-distributions), re-open the PR and merge once all PRs are ready. WDYT?

**Comment by mswiderski** [comment]
correct, these should not be merged without jbpm related one

**Comment by csadilek** [comment]
@mswiderski @psiroky I missed that, sorry. Merged too many PRs lately. Any chance we can get the upstream change in or do you want me to revert?

**Comment by mswiderski** [comment]
better to revert as PRs in jbpm and droolsjbpm-integration eating for review and since these are quite a big PRs it can take few days more. Like beginning of next week

**Comment by csadilek** [comment]
@mswiderski @psiroky ok reverted. I guess this also needs to be reverted from kie-wb-distributions? I will do that now.

**Comment by csadilek** [comment]
reverted: 88cb5f6f1b6ae6de77084d383a94387f33581cd1

**Comment by mswiderski** [comment]
ok, this one is now ready to be merged

**Comment by csadilek** [comment]
master: 3ed6adb53b73f9216dc94c7f0a89660765d25f0a

**Pull request closed without merging**
