### PR TITLE
BZ1007859 - Add 'select all' checkbox to Process instances

### PR DESCRIPTION
**Pull request by nmirasch**
Use ResizableHeader from uberfire-ext.
Change the check column, adding the header for select all instances. Depending on https://github.com/uberfire/uberfire-extensions/pull/277

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Hi @nmirasch looking really good! Only two details I would like to add:
- Give a fixed width to the check column enough to display the check box, so we can have more spce available to the other columns.
- When I bulk abort all instances I had active, the column header was left with a check state that I couldn't uncheck. Should we review to clean the check status when the table becomes empty? See screenshot.

selection_083

**Comment by nmirasch** [comment]
@cristianonicolai done. Can you take a look? Thanks!

**Comment by cristianonicolai** [comment]
@nmirasch looks good now, just missing the fixed width.

**Comment by nmirasch** [comment]
@cristianonicolai  now this pr depends on https://github.com/uberfire/uberfire/pull/366

**Comment by cristianonicolai** [comment]
+1 Looks great, thanks @nmirasch!

Waiting for https://github.com/uberfire/uberfire/pull/366 to get merged so I can merge this one as well.

**Pull request merged**
