### PR TITLE
RHBPMS-2059 - Pull latest translations from Zanata

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mbiarnes could you please review, thanks.

**Comment by manstis** [comment]
Did you run the ```replacer:replace``` maven goal? I see single apostrophes exist.. but this'll cause problems with GWT compilation (for "full profile") - as we need to escape single apostrophes with two single apostrophes. Jenkins has done a "fast compile" - only 2 permutations; so FR was skipped.

**Comment by manstis** [comment]
@cristianonicolai You can get the gory details from @mbiarnes of what steps need to be performed between fetching translations from Zanata and pushing to github... (please!)

**Comment by mbiarnes** [comment]
I did mvn zanata:pull-module and mvn replacer:replace -N locally and I don't see these changes. Looking in scripts there is a mvn replacer:replace -N. I don't know why this did not work properly.
I think this PR can be closed.

**Comment by cristianonicolai** [comment]
@mbiarnes @manstis thanks, this PR is incorrect, as you saw I forgot to run `replacer:replace`. There is another PR already fetching the new translations for 6.5.x (https://github.com/droolsjbpm/jbpm-console-ng/pull/475). Closing this one.

**Pull request closed without merging**
