### PR TITLE
Rename jbpm-console-ng-business-domain module to jbpm-console-ng-kie-…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…server

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/316

**Comment by manstis** [comment]
@nmirasch Could you please review?

**Comment by nmirasch** [comment]
@cristianonicolai even the git doesn't show conflicts, I hat problems to test this pr after the last merged commit https://github.com/droolsjbpm/jbpm-console-ng/commit/db6e154f28c3712318af1420be31076f7c6d9d76, can you update the commit? Thanks!

**Comment by cristianonicolai** [comment]
@nmirasch sure. PR rebased on latest master, thanks.

**Pull request merged**
