### PR TITLE
BZ-1172069 User do not know what happens after click Start Process button

### PR DESCRIPTION
**Pull request by bxf12315**

### CODE REVIEW

**Comment by psiroky** [comment]
The BZ number seems to be wrong, its point to some bug completely unrelated to this.

@Salaboy @bxf12315 is this PR still relevant?

**Comment by bxf12315** [comment]
@psiroky Sorry , this BZ number is 1172069
https://bugzilla.redhat.com/show_bug.cgi?id=1172069
Sorry again.

**Comment by psiroky** [comment]
@bxf12315 there are merge conflicts right now. Could you please take a look and update the PR, so that it can be cleanly merged (you can force push to this branch, no need to create new PR).

**Comment by bxf12315** [comment]
@psiroky  ok no problem

**Comment by Salaboy** [comment]
@bxf12315 are you planning to update this PR?

**Comment by bxf12315** [comment]
@Salaboy  yes,

**Comment by bxf12315** [comment]
@Salaboy  hi , i updated the PR, please review it.

**Comment by Salaboy** [comment]
This is in conflict at this point, needs to be fixed

**Comment by bxf12315** [comment]
I will refacing it according Kris's suggestion

**Comment by bxf12315** [comment]
@Salaboy @cristianonicolai 
I was update the PR, just disable submit button after click it.
So please check it.

**Comment by mswiderski** [comment]
and why not closing the window immediately? In case of error there will be another popup window shown anyway...

**Comment by bxf12315** [comment]
@mswiderski  if first node of process is synchronous work-item and takes a long time to execute, when use click create process button,
create process popup form will  stays in place for dozens of seconds. User can not know what's happen and user can click the button again. If use  async work-item ,  the  dialog also stays in place for few seconds(less then synchronous workitem). 
I will send you a mail , include Kris and Joe's suggestion.

**Comment by mswiderski** [comment]
I understand, what I suggesting is to close the window before sending request to backend for processing the request like start process. I assume form validation is client side anyway so that should be possible.

**Comment by bxf12315** [comment]
@mswiderski  Our current logic is the popup form close after start process is successful. If start process is failure , the form will stay in place.

**Comment by mswiderski** [comment]
and what's the reason for the form to stay there? Since it failed doesn't make sense to submit again same form (not even sure you will be able to). Similar if you disable the start button the form is sort of useless after first use.
What's even worse from usage point of view error will be displayed on new popup window and user would then have to close two windows ... 
P.S.
Didn't want to steel the thread here but just wondering what would we gain with such change... if no one else thinks similar to me then it means it's my problem and not the app so I stay quiet :)

**Comment by bxf12315** [comment]
@mswiderski   Understood, In my side, I think you are right. 
We should close the form , whatever start  process is success or failure .
If process is failure , we just need show error message form. if success , we can show some successful message.

**Comment by bxf12315** [comment]
@Salaboy @cristianonicolai @mswiderski 
I was update the PR, according @mswiderski 's suggestion.
Close start process form , whatever start is success or failure.
If process is failure , we just need show error message form. if success , we can show some successful message.
So please check it.
PS: I will send video to you, that is this feature video.

**Comment by cristianonicolai** [comment]
@bxf12315, I got a simplified version of your PR in here: https://github.com/cristianonicolai/jbpm-console-ng/commit/2fc787e2dfa04da64f7d7b846c834558860bd44e

Could you please try it out and check if it fixes the issue? Thanks.

**Comment by cristianonicolai** [comment]
A new PR has been opened to address this issue: https://github.com/droolsjbpm/jbpm-console-ng/pull/232

**Pull request closed without merging**
