### PR TITLE
Refactor and cleanup duplicated code for defining screens menus

### PR DESCRIPTION
**Pull request by cristianonicolai**
Consolidated code for refresh, refresh selector and reset default filters
Removed duplicated close menu from screens
Added unit test for new menu builders

### CODE REVIEW

**Comment by csadilek** [comment]
@cristianonicolai Nice cleanup! Can we add some tests to this with a reasonable amount of effort? The whole project seems very low on test coverage. Also, are you sure you want this change on 6.4.x as well (bit of a risk but definitely fine with me).

**Comment by cristianonicolai** [comment]
@csadilek sure, tests are always helpful :) I added one unit test class per builder class that I created for this change. As for 6.4.x I think still worthwhile to merge as we can potentially reduce any effort on maintenance for this branch.

**Comment by csadilek** [comment]
+1, thanks @cristianonicolai.

**Comment by csadilek** [comment]
master: a43a9bb5f6edeae0ec4333979de24c99a38dd953

**Pull request closed without merging**
