### PR TITLE
 BZ-1165089 - [RFE]process initiator（or process admin） can not check pro...

### PR DESCRIPTION
**Pull request by bxf12315**
...cess instance history details

                 1 add usertask log tab page
                 2 add popup user task work details

### CODE REVIEW

**Comment by psiroky** [comment]
The mentioned BZ is marked as verified. @bxf12315 can we close this PR?

**Comment by bxf12315** [comment]
@psiroky not really, we need refacing instance details tab and log tab. 
Now i doing this work, next week i will raise new PR.

**Comment by psiroky** [comment]
@bxf12315 So does this relate to the original BZ-1165089? If so please re-open it or create new one and link it here. Having open PR against closed BZ is confusing.

**Comment by bxf12315** [comment]
@psiroky , this fix code, not good enough .we will raise new PR for this.
this PR i will closed.
Thanks!

**Pull request closed without merging**
