### PR TITLE
JBPM-4870: Process dashboard MVP & Unit testing

### PR DESCRIPTION
**Pull request by dgutierr**
This PR it's a refactor of the UI layer in order to comply with the MVP best practices. In a nutshell:

* Ensure all UI components follow the MVP (Model View Presenter) pattern in order to ensure a clear separation between "the view", "the presenter" and "the model".

* In such model, The presenter must not contain any widget reference and the model must not "touch" the view as well. The presenter must provide the required logic to pass & update the view with the required information.

* MVP applicability ensures the logic in the presenter can be properly tested using junit/mockito tests. Along with the refactor several unit tests over the presenter components are provided.

     IMPORTANT NOTE: This PR depends is tied to dashbuilder/dashbuilder#78 and MUST be merged at the same time on master, otherwise the build will fail.

### CODE REVIEW

**Comment by romartin** [comment]
Testing it by running the app in super dev mode (just command line), all displayers are showing the error message "java.lang.RuntimeException: Data set not found: processesMonitoring".

**Comment by romartin** [comment]
This issue about the missing data set defintiion in the jbpm-console is not produced by the refactor. I have tested it without it and it still fails. The refactor works fine as the process dashboard is working on both workbenches.

Opened a JIRA for this concrete showcase's issue -> https://issues.jboss.org/browse/JBPM-4882

+1 for merging the PR

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
Thanks.

master: 2caa7d0c27328f37038e10699622e9d5d81810d1

**Pull request closed without merging**
