### PR TITLE
BZ-1172069 User do not know what happens after click Start Process bu…

### PR DESCRIPTION
**Pull request by bxf12315**
…tton
include: unit test and mswiderski's comment.
It is dependent on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/113

### CODE REVIEW

**Comment by bxf12315** [comment]
@cristianonicolai @Salaboy @nmirasch  @mswiderski @manstis 
Please review it. 
Thanks

**Comment by bxf12315** [comment]
@cristianonicolai  I updated the PR base on your PR.
Please reivew it.

**Comment by porcelli** [comment]
@bxf12315 @cristianonicolai  is this still makes sense?

**Comment by bxf12315** [comment]
@porcelli i think yes.

**Comment by bxf12315** [comment]
@cristianonicolai @porcelli  @nmirasch @mswiderski 
I think the PR is incorrect , because of we can not hide start-process-form when click submit.
If form's field check is wrong , the logic is incorrect.
So I refacing it , remove hide logic.

**Pull request closed without merging**
