### PR TITLE
JBPM-4834 - Enable admin tab on tasks selected from admin filter

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/dashbuilder/dashbuilder/pull/125

**Comment by cristianonicolai** [comment]
Awaiting for https://github.com/droolsjbpm/jbpm-console-ng/pull/301 to get merged so I can push this change into master as well.

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: e15110c40651d1ac3aede1354ffbbfe889d6eed4

**Pull request closed without merging**
