### PR TITLE
JBPM-4647 - Case instance roles

### PR DESCRIPTION
**Pull request by cristianonicolai**
UI building block for managing case roles assignment.

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch @mswiderski another building block for review please.

**Comment by cristianonicolai** [comment]
@csadilek please have a look if this is better use of Errai UI, thanks.

**Comment by nmirasch** [comment]
+1

**Comment by mswiderski** [comment]
looks good to me, +1

**Comment by csadilek** [comment]
@cristianonicolai +1. Though NewRoleAssignmentViewImpl is still using widgets as data fields (the gwt bootstrap 3 types e.g. Input, which is a widget not just a DOM wrapper).

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
jenkins retest this.

**Pull request merged**
