### PR TITLE
BZ-12743446: fixing domain specific data pagination issue

### PR DESCRIPTION
**Pull request by Salaboy**
MVP initial refactoring + GWT Mockito Test added

### CODE REVIEW

**Comment by Salaboy** [comment]
ready for review

**Comment by csadilek** [comment]
@Salaboy looks good! Big improvement in my opinion plus it contains a test for the fix now. Are you gonna send a separate PR for 6.3.x or do you want me to attempt and merge this there as well?

**Comment by csadilek** [comment]
+1, for both branches, but waiting for @Salaboy to clarify.

**Comment by Salaboy** [comment]
@krisv based on the changes do yo think that is safe to move that to 6.3.x at this stage? I haven't smoke tested enough yet in master to verify the changes in 6.3.x

**Comment by krisv** [comment]
+1, with a quick look it seems fine to include this in 6.3.x as well

**Comment by csadilek** [comment]
Just to clarify for others. This still needs confirmation from @salaboy (who's testing on 6.3.x) before it can be merged.

**Comment by Salaboy** [comment]
Unfortunately I couldn't get it working on 6.3.x.. it is a different codebase with BS2 and on testing in kie-wb wasn't working due some other changes in 6.3.x branch. I will start fresh tomorrow morning

**Comment by csadilek** [comment]
@Salaboy I am happy to help / pair up if you think it makes sense.

**Comment by Salaboy** [comment]
@csadilek I appreciate the intention, but I don't think that you need to worry about this. I will try to get it done asap

**Pull request closed without merging**
