### PR TITLE
JBPM-5530 - Combine new forms API into jbpm-wb-forms modules

### PR DESCRIPTION
**Pull request by cristianonicolai**
Updated packages from condole.ng to workbench
Updated GWT modules names

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/362

**Comment by cristianonicolai** [comment]
@pefernan please help review. As we discussed, I moved all new form related classes into a common module. Let me know if the new structure, including packages looks fine to you.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by cristianonicolai** [comment]
Jenkins please retest this.

**Comment by pefernan** [comment]
+1

**Pull request merged**
