### PR TITLE
Case Roles: Re-factor existing and add new tests

### PR DESCRIPTION
**Pull request by bsremac**
Commit consists of: 
1. Re-factored existing Case Roles tests, mainly around test data initialization (so that parent test class is used more and common data shared among tests) and more efficient verification in some tests.
2. New tests aiming to cover in more details code branching at certain places in Presenter class

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@bsremac would you mind to squash these commits into a single one?

**Comment by bsremac** [comment]
jenkins please retest this

**Comment by bsremac** [comment]
@cristianonicolai I squashed the commits into one. Apologies for the mess around multiple redundant commits.
@jhrcek I added AssertJ library, only to this module, and used it in two tests which require multiple subsequent assertions. The assertions indeed look concise (and assertion errors are more informative)

**Comment by cristianonicolai** [comment]
thanks @bsremac!

**Pull request merged**
