### PR TITLE
JBPM-9807 Additional information in the Task Logs page in Business Ce…

### PR DESCRIPTION
**Pull request by bxf12315**
…ntral

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[https://issues.redhat.com/browse/JBPM-9807](JBPM-9807)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
> image @bxf12315 It seems the event when forwarding bringing the getAssignedOwner in TaskEventSummary Could be possible to add the constant for forwarded there to see it well even just in english?

updated

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by prashuts** [comment]
Jenkins run fdb

**Comment by nmirasch** [comment]
image
@bxf12315 when the task is forwarded the destination id of the user is still not shown at logs.

**Comment by bxf12315** [comment]
> image @bxf12315 when the task is forwarded the destination id of the user is still not shown at logs.

after fowwarded, task status is claimed, it doesn't have a potential owner.

**Comment by nmirasch** [comment]
@bxf12315 I agree that when the task is forwarded there is no actual owner. but the 'forward' operation was done with some value in 'user' field.
image

We have two options. Add the new potential owner added in the 'forward' operation to the current log "Task forwarded by user wbadmin to user XXX" or to change the log message  without the destination information, just "Task forwarded by user wbadmin"

**Comment by bxf12315** [comment]
> @bxf12315 I agree that when the task is forwarded there is no actual owner. but the 'forward' operation was done with some value in 'user' field. image
> 
> We have two options. Add the new potential owner added in the 'forward' operation to the current log "Task forwarded by user wbadmin to user XXX" or to change the log message without the destination information, just "Task forwarded by user wbadmin"

For now, it's impossible, because of TaskEventInstance just has assignedOwner [1]. 


[1] https://github.com/kiegroup/droolsjbpm-integration/blob/7c65ce70337424dbc14df3ebbfb6b6b84e34603d/kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/TaskEventInstance.java#L61

**Comment by nmirasch** [comment]
@bxf12315 that's fine, then IMO it seems we need to remove 'to user' from log. @prashuts what do you think?

**Comment by prashuts** [comment]
Agreed that ''to user'' does not give any sense. Better to remove.

**Comment by bxf12315** [comment]
> @bxf12315 that's fine, then IMO it seems we need to remove 'to user' from log. @prashuts what do you think?

Done

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Review by nmirasch — APPROVED** [review]

**Comment by barboras7** [comment]
Hi @bxf12315,
I checked the PR and I have only one question. In the Jira description, it is stated that the desired behavior is following:
`When a task is delegated by UserA to UserB, tasks logs page should display such information in the following form: Task delegated by UserA to UserB.`

Now, in your implementation, the statement in the log is following:
`Task delegated by user UserA to user UserB` instead of `Task delegated by UserA to UserB` (as described in the requirement). 

Even though the difference is just small, I wanted to point it out to double-check that the implementation that you provided is correct.

**Comment by bxf12315** [comment]
> Hi @bxf12315, I checked the PR and I have only one question. In the Jira description, it is stated that the desired behavior is following: `When a task is delegated by UserA to UserB, tasks logs page should display such information in the following form: Task delegated by UserA to UserB.`
> 
> Now, in your implementation, the statement in the log is following: `Task delegated by user UserA to user UserB` instead of `Task delegated by UserA to UserB` (as described in the requirement).
> 
> Even though the difference is just small, I wanted to point it out to double-check that the implementation that you provided is correct.

You can see "Task activated by user admin" and "Task added by user wbadmin". I just want to keep them same.
@nmirasch WDYK?

**Comment by nmirasch** [comment]
@bxf12315 Yes, I agree with you, to me is more consistent with other logs adding 'by user .." when is an specific user is performing the action. Maybe is a matter of commenting that on jira, to be sure this fits the requirements

**Comment by barboras7** [comment]
Thank you, looks good :tada:

**Review by barboras7 — APPROVED** [review]

**Comment by jstastny-cz** [comment]
Are we only waiting for green PR checks here?

**Comment by bxf12315** [comment]
@nmirasch Can we merge it?

**Comment by nmirasch** [comment]
@bxf12315 Could you mind to rebase this one?. It was committed three months ago, I prefer do a rebase before merge. Thanks!

**Comment by nmirasch** [comment]
Jenkins run fdb

**Pull request merged**
