### PR TITLE
Move task detail logs to own tab so it is consistent with process ins…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…tance details.

### CODE REVIEW

**Comment by Salaboy** [comment]
+1

**Comment by csadilek** [comment]
I know this can be seen as mainly a refactoring but it would still be nice to have some test coverage i.e. for the event observers to make sure they call refreshLogs.

**Comment by cristianonicolai** [comment]
PR updated, now with tests :)

**Comment by csadilek** [comment]
Great! Thanks!

master: 8fa9a95e8d1eeae40367fe26dac02f727669cd24

**Pull request closed without merging**
