### PR TITLE
JBPM-4812 - Allow to query by task variables - added new entity to pe…

### PR DESCRIPTION
**Pull request by mswiderski**
…rsistence.xml

### CODE REVIEW

**Comment by mswiderski** [comment]
depends on https://github.com/droolsjbpm/jbpm/pull/338

**Comment by cristianonicolai** [comment]
+1

**Comment by csadilek** [comment]
Dependent on PRs not merged yet. So waiting with this one.

**Comment by mswiderski** [comment]
I plan to merge all depending PRs later today. I can go ahead with this one (and kie-wb too) to make sure all are pushed. Or shall I drop comment here when core repositories are merged?

**Comment by csadilek** [comment]
@mswiderski whatever you prefer ;). Just wasn't sure if it's ready as the other PRs were still open and are listed as dependent on.

**Comment by mswiderski** [comment]
merged into master

**Pull request closed without merging**
