### PR TITLE
Fixing master's compilation failures

### PR DESCRIPTION
**Pull request by afcollins**
Master was not building due to recent DASHBUILDER-58/60 refactorings.

### CODE REVIEW

**Comment by Salaboy** [comment]
@afcollins It think the two PR that you merged in here are being reviewed, that's why it is still failing

**Comment by csadilek** [comment]
@Salaboy I don't think there are PRs with pending reviews. The way I understand it we're waiting for @nmirasch's PR for master based on the recent dashbuilder refactorings, or did I misunderstand?

**Comment by afcollins** [comment]
@csadilek You're correct.  Just thought to fix compilation errors while refactoring is taking place, so this (and kie-wb) will still build.

**Comment by Salaboy** [comment]
@csadilek you are correct, I've checked with @nmirasch  and she is working on that

**Comment by afcollins** [comment]
Closing as will be fixed by @nmirasch

**Pull request closed without merging**
