### PR TITLE
PLANNER-707: Workbench "import example dialog": Embed stock example repositories

### PR DESCRIPTION
**Pull request by mcimbora**
Remove repository initialization from AppSetup

The examples will be moved from https://github.com/droolsjbpm/jbpm-playground to https://github.com/droolsjbpm/kie-wb-playground. This might be a good place to discuss which examples should be included in the workbench by default.

### CODE REVIEW

**Comment by mcimbora** [comment]
Depends on
- https://github.com/droolsjbpm/kie-wb-common/pull/622
- https://github.com/droolsjbpm/kie-wb-distributions/pull/437

**Comment by mcimbora** [comment]
@cristianonicolai Can you please review the PR and add your thoughts about migration of jbpm-playground examples to https://github.com/droolsjbpm/kie-wb-playground?

**Comment by mcimbora** [comment]
Not complete, adding examples import to project authoring perspective.

**Comment by mcimbora** [comment]
Updated.

**Comment by cristianonicolai** [comment]
@mcimbora thanks this looks good, my only comment is around the org.kie.demo system property which was useful specially for development to get the example installed once the wb starts. Could we still keep it?
As for the jbpm-playground we need to evaluate which projects still relevant for migration. I believe some are even broken if used on current master.

**Comment by mcimbora** [comment]
@cristianonicolai Sure, I see the point in keeping the property. Once the jBPM examples are included in the jar, there will be no need to fetch them from external location (github). I can implement initial filtering based on tags, so that only relevant examples are imported here. Example repository https://github.com/droolsjbpm/kie-wb-playground currently contains 2 examples (Drools/OptaPlanner), it would be nice to add at least one from jBPM side for now. Can you suggest a working candidate?

**Comment by cristianonicolai** [comment]
@mcimbora I think we could start with the "evaluation" project. @krisv, @mswiderski wdyt?

**Comment by krisv** [comment]
The evaluation one if by far the most important one imho, as it's used as the quickstart example.

**Comment by mcimbora** [comment]
@cristianonicolai Reverted org.kie.demo property usage. I created PR to add evaluation project into kie-wb-playground repository https://github.com/droolsjbpm/kie-wb-playground/pull/6

**Comment by cristianonicolai** [comment]
@mcimbora looks good, thanks!

**Pull request merged**
