### PR TITLE
JBPM-4767: Process/Task dashboard details screen (in log mode) switch…

### PR DESCRIPTION
**Pull request by nmirasch**
… to default after refresh

### CODE REVIEW

**Comment by cristianonicolai** [comment]
See comments on https://github.com/droolsjbpm/jbpm-console-ng/pull/331

**Comment by cristianonicolai** [comment]
+1

**Comment by psiroky** [comment]
@nmirasch could you please rebase this on top of the current master and fix the merge conflicts (they were introduced after merging one of the other PRs)?

**Comment by nmirasch** [comment]
@psiroky done!

**Comment by csadilek** [comment]
master: a6d803a7f83b6b082117916c9613461d044c3969

**Pull request closed without merging**
