### PR TITLE
JBPM-5421 - Remove document support from jbpm-console-ng

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch could you please have a look? :)

**Comment by cristianonicolai** [comment]
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/318

**Comment by nmirasch** [comment]
@cristianonicolai can you rebase the commit with master? Thanks!

**Comment by cristianonicolai** [comment]
@nmirasch done :)

**Comment by nmirasch** [comment]
+1

**Pull request merged**
