### PR TITLE
[6.5.x] ports for JBPM-5249

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
needs to be retested once https://github.com/droolsjbpm/jbpm-designer/pull/382 is merged

**Comment by tsurdilo** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
still needs droolsjbpm/jbpm-designer#382 to be merged..will ask retest after

**Comment by tsurdilo** [comment]
resolved conflict and waiting still on  droolsjbpm/jbpm-designer#382 to re-run tests

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
@tsurdilo what's up with the first commit here: DDConfigUpdater - fix for 6.5.x / java 1.6

Can you either squash it or change the title, please? We don't want the branch name in the commit message and DDConfigUpdate alone doesn't really mean anything....

**Comment by tsurdilo** [comment]
@csadilek done. let me know if it's still not good. thanks

**Comment by csadilek** [comment]
+1

**Pull request merged**
