### PR TITLE
KIE forms jBPM integration:

### PR DESCRIPTION
**Pull request by pefernan**
- Support for BeanValidation for dynamic models
- Fixing minor issues

KIE forms jBPM integration:
- Fixing binding strategy for jBPM

Merge with: https://github.com/droolsjbpm/kie-wb-common/pull/572

This PR reverts droolsjbpm/jbpm-console-ng#567

@cristianonicolai this is the easiest way I found to do it ;)

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins reterst this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
@cristianonicolai https://github.com/droolsjbpm/kie-wb-common/pull/572 has been merged

**Comment by psiroky** [comment]
@pefernan I am assuming the jbpm-console-ng build is broken, because the upstream kie-wb-common PR was merged and this one wasn't. Is that correct?

**Comment by psiroky** [comment]
Merging as the same changes were approved by https://github.com/droolsjbpm/jbpm-console-ng/pull/560, which was than reverted, because the kie-wb-common PR wasn't merged at the same time.

**Pull request merged**
