### PR TITLE
Fixing findbugs warnings

### PR DESCRIPTION
**Pull request by jhrcek**
Fixed all (3) occurrences of "Method may fail to close stream"

### CODE REVIEW

**Comment by jhrcek** [comment]
Hello @mrietveld Could you please review this PR with few findbugs warnings fixes, one of them related to your recent work?

**Comment by Salaboy** [comment]
Hi @jhrcek I was looking at the PR, and it seems the right way to go. That's how you should handle input streams in general right? Should I merge this one? I don't see a reason why not.

**Comment by mrietveld** [comment]
+1

**Comment by Salaboy** [comment]
merged in master

**Pull request closed without merging**
