### PR TITLE
get rid of super `smart` use of toString()

### PR DESCRIPTION
**Pull request by porcelli**
... if I knew who did this :P

### CODE REVIEW

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: de2a7deb0b4ce3cfbe1cff1e8ba745c7ff184ef0

**Comment by triceo** [comment]
If only the actual changes weren't being obfuscated by too many irrelevant whitespace changes...

**Comment by porcelli** [comment]
@triceo https://github.com/droolsjbpm/jbpm-console-ng/commit/de2a7deb0b4ce3cfbe1cff1e8ba745c7ff184ef0?w=1

**Comment by triceo** [comment]
Awesome, much appreciated @porcelli !

**Comment by porcelli** [comment]
@triceo btw: i completely agree that formating is annoying, but we need to fix this in the root and make sure that everyone follow the same formating rules - what we have already defined.

**Comment by triceo** [comment]
@porcelli Can you think of a way to make this happen? It's not in my powers to enforce this, nor do I want to. :-)

**Comment by porcelli** [comment]
@triceo hehe.. i'll do my best ;)

**Pull request closed without merging**
