### PR TITLE
Added logging in case (un)deployment fails

### PR DESCRIPTION
**Pull request by selrahal**

### CODE REVIEW

**Comment by psiroky** [comment]
@Salaboy @mswiderski this seems like a safe changed. What do you think?

**Comment by mswiderski** [comment]
fine with me, but not sure it makes sense to push it to 6.0.x, are we planning o make any further releases of 6.0.x?

**Comment by psiroky** [comment]
@mswiderski good catch, I overlooked the 6.0.x. I think we should merge this into master only (at least for now).

**Comment by Salaboy** [comment]
@psiroky @mswiderski should I go ahead and merge this in master?

**Comment by Salaboy** [comment]
merged in master

**Pull request closed without merging**
