### PR TITLE
Remove unused/outdated perspectives, presenters and views

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch @Salaboy please have a look once you have a chance. I believe all of these have been replaced already for new versions.

**Comment by mswiderski** [comment]
I like this one ... can we get this reviewed and merged so I move on with remove of jBPM runtimes from console?

**Comment by nmirasch** [comment]
+1 @cristianonicolai thanks!

**Comment by csadilek** [comment]
+1. My favourite type of commit!!

**Pull request merged**
