### PR TITLE
Fix for JBPM-4963, JBPM-4973, BZ1285247, BZ1285243 and BZ1285198 Cent…

### PR DESCRIPTION
**Pull request by nmirasch**
…ralize dateTimeFormatting

### CODE REVIEW

**Comment by manstis** [comment]
There's date and date-time formats available in ApplicationPreferences - that's loaded and initialised in each Web Apps EntryPoint.. you might like to reuse that to keep some consistent use of date and date-time formats.

**Comment by nmirasch** [comment]
@manstis now ApplicationPreferences.getDroolsDateTimeFormat() is used to load the date-time format.

**Comment by manstis** [comment]
Good job neus, thanks. 

It might be an idea to add some tests for ApplicationPreferences provided date/date-time formats but not essential.

+1 to merge.

**Comment by cristianonicolai** [comment]
looks great, thanks @nmirasch !

**Comment by csadilek** [comment]
6.4.x: 52c5afe1cd8e11c17eb3ed2bfc6f888b0e3bb813

**Pull request closed without merging**
