### PR TITLE
BZ-12743446: fixing domain specific data pagination issue

### PR DESCRIPTION
**Pull request by Salaboy**
This PR fix the stated BZ and it can be applied in master and cherry picked to 6.3.x

### CODE REVIEW

**Comment by Salaboy** [comment]
@csadilek can you please review and merge this asap to 6.3.x and master, so it can be picked in the next build. Thanks

**Comment by csadilek** [comment]
@Salaboy this is a -1 from me because of the missing test. I don't see why it's not possible to write a unit test for the presenter like everyone else does.

**Comment by Salaboy** [comment]
I've just added a test + the MVP refactoring to make this particular screen more easy to test. It is ready to be reviewed

**Comment by Salaboy** [comment]
I'm closing this PR to send a new one with the commits squashed

**Pull request closed without merging**
