### PR TITLE
Fix to include uberfire-security-management-* compile source artifacts

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by nmirasch** [comment]
I think we need here add <inherits name="org.uberfire.ext.security.management.UberfireSecurityManagementClient"/>  too

**Comment by paulovmr** [comment]
Hi @nmirasch , this line is going to be added in kie-wb-common, by this PR: https://github.com/droolsjbpm/kie-wb-common/pull/525/files

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by nmirasch** [comment]
@paulovmr ok, waiting for that merge then, Thanks!

**Comment by csadilek** [comment]
jenkins retest this (jbpm issue resolved.)

**Comment by csadilek** [comment]
+1

**Pull request merged**
