### PR TITLE
I18n overall fixes

### PR DESCRIPTION
**Pull request by cristianonicolai**
Added internationalization to various strings

### CODE REVIEW

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: 01b008b79365f93e2ae5cf5d0513ce61f179b0c7

**Comment by csadilek** [comment]
@cristianonicolai Should this go into 6.4.x as well?

**Comment by cristianonicolai** [comment]
@csadilek merged on 6.4.x already https://github.com/droolsjbpm/jbpm-console-ng/commit/544fd786c4857f62ff2d933ec5e39f719d3c3e20

**Pull request closed without merging**
